<a href="https://colab.research.google.com/github/yashbhoyar2/docs/blob/master/Day_50_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
a.ndim

1

In [5]:
a.shape

(4,)

In [7]:
m=np.arange(1,10)
print(m)

[1 2 3 4 5 6 7 8 9]


In [8]:
m=np.arange(1,10,2)
print(m)

[1 3 5 7 9]


In [9]:
m=np.arange(1,10,0.5)
print(m)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [10]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [11]:
print(np.linspace(0,100,20)) # gives equally spaces to plant trees

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [12]:
np.linspace(1,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Output will be in Float in "linspace"

In [13]:
a=np.array([1,2,3,4,5,6,7,8])

In [14]:
type(a)

numpy.ndarray

In [15]:
a.dtype # d type is datatype

dtype('int64')

In [ ]:
# dtype is attribute

In [17]:
a=np.array([1,2,3,4,5,6,7,8.5])
print(a)

[1.  2.  3.  4.  5.  6.  7.  8.5]


In [18]:
a.dtype

dtype('float64')

In [20]:
a=np.array([1,2,3,4,5,6,7,'8.5'])
print(a)

['1' '2' '3' '4' '5' '6' '7' '8.5']


In [21]:
a.dtype

dtype('<U21')

In [ ]:
# Unicodes type

In [22]:
a=np.array([1,2,3,4,5,6,7,'8.5',4.5])
print(a)

['1' '2' '3' '4' '5' '6' '7' '8.5' '4.5']


In [23]:
a.dtype

dtype('<U32')

In [ ]:
# 32 is bytes

In [26]:
a=np.array([1,2,3,4,5,6,7], dtype="float64")
print(a)
print(a.dtype)

[1. 2. 3. 4. 5. 6. 7.]
float64


In [ ]:
# It forcefully convert to float

In [28]:
100**10

100000000000000000000

In [27]:
b=np.array([10,100])
b**10

array([        10000000000, 7766279631452241920])

In [ ]:
# Numpy has limit. so it will wrap

In [29]:
b=np.array([100])
b**10

array([7766279631452241920])

In [30]:
# 2D Array

In [31]:
m1=np.array([[1,2,3],[4,5,6]])
print(m1)

[[1 2 3]
 [4 5 6]]


In [32]:
m1.ndim # number of dimension

2

In [33]:
m1.shape

(2, 3)

In [34]:
len(m1) 

2

In [36]:
# Quiz
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(len(m1))

3


In [37]:
m1.shape

(3, 3)

In [39]:
m2=np.arange(1,13)
print(m2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# make it 2D, so use reshape

In [44]:
m2.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
m2.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [46]:
m2.reshape((2,-1))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [47]:
m2.reshape((-1,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
m2.reshape((-1,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
# -1 will give number of row and column

In [49]:
m2.reshape((-1,5)) # error: cannot reshape array of size 12 into shape (5)

ValueError: ignored

In [51]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
# Quiz
np.arange(1,17).reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
# reshape is to check row and column

In [52]:
m2=np.arange(1,13)
print(m2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [53]:
m2.shape

(12,)

In [54]:
# we can make 2d array of it
m2.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [55]:
m2.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
# comes with two brack i.e 2D

In [ ]:
# Transpose 
# (Convert rows to column and column to rows)

In [56]:
m5=np.arange(1,13).reshape(3,4)
print(m5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
m5.T # T is for Transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [58]:
m6=m5.T
m6.shape

(4, 3)

In [59]:
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
m2.T # We can't do transpose for 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
m7=m2.reshape(1,12) # we can do transpose by reshape 

In [63]:
m7

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [66]:
m8=m7.T
print(m8)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [67]:
m8.shape

(12, 1)

In [68]:
m5=np.arange(1,13).reshape(3,4)
print(m5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# we can convert it in to 1D. means flatten.

In [69]:
m5.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
m8=m5.flatten()

In [71]:
m8.shape

(12,)

In [72]:
# If we want access of perticular element in 3x3 array
m5=np.arange(1,10).reshape(3,3)
print(m5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
m5[0][1]

2

In [74]:
m5[1][1]

5

In [75]:
# [0,0,0] 1D array
np.zeros(3)

array([0., 0., 0.])

In [77]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
n=np.ones((3,4))

In [79]:
n*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [80]:
n*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [82]:
np.full((3,4),2.0)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
# Diagonal Array (Matrix)
# [.   
#   .  
#    .
#     .]

In [83]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [84]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [85]:
# Identity is square matrix K X K
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
n1=np.identity(5)
print(n1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [87]:
n1*4 # my question, with diff number

array([[4., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 4.]])

In [88]:
# Access Numbers ---------- by indices-------list must require
n3=np.array([1,2,3,4,5,6,7,8,9])
n3[[1,3,5,7]]

array([2, 4, 6, 8])

In [89]:
n3[[1,3,5,7]]

array([2, 4, 6, 8])

In [90]:
# Lets find from 2D array------by indices
m4=np.arange(1,10).reshape(3,3)
print(m4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [92]:
m4[[0,1,2],[1,2,0]]    # here first bracket will find by row indices and 2nd bracket will find by column indices. i.e (0,1), (1,2), (2,0)

array([4, 8, 3])

In [93]:
m4[[1,2,0],[0,1,2]] 

array([4, 8, 3])

In [94]:
m4[[1,2,0,0],[0,1,2,0]] # we can add numbers as many as we want

array([4, 8, 3, 1])

In [95]:
n5=np.arange(12)
n5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
# If we want to access 0,  1,  2,  3,  4
n5[:5]

array([0, 1, 2, 3, 4])

In [97]:
# Lets access from 2D array
n6[:,(0,2)]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
n6[:2, :] # 0&1, all rows

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
n6[:,:2] # Access all column

array([[1, 2],
       [4, 5],
       [7, 8]])

In [100]:
n6[:,: :] # All column and all rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
n6[:,: :2] # step is 2, then it will take 0 and 2 column

array([[1, 3],
       [4, 6],
       [7, 9]])

In [102]:
n6[:,(0,2)] # All rows and 0 and 2 indices column

array([[1, 3],
       [4, 6],
       [7, 9]])

In [103]:
n6[1, :2]

array([4, 5])

In [105]:
# Quiz
n7=np.arange(12).reshape(3,4)
print(n7)
n7[0,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([1, 2])

In [108]:
n7[0,0]=99
print(n7)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [110]:
n8=np.arange(12)
n8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [112]:
n8[2:]=98
n8

array([ 0,  1, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98])

In [113]:
n8[:2]=98,98
n8

array([98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98, 98])

In [115]:
# Quiz
n8 = np.arange(6)
n8[4:]=10
print(n8)

[ 0  1  2  3 10 10]


In [117]:
n8=np.arange(6)
n8[:3]=10,20,30
print(n8)

[10 20 30  3  4  5]


In [118]:
# Quiz
a=[1,2,3,4,5]
b=[8,7,8]
a[2:]=b[::-1]
print(a)

[1, 2, 8, 7, 8]


In [134]:
# Doubts session
D5=np.arange(1,13).reshape(3,4)
print(D5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [135]:
D5[0][3] # 1st option: we can write this also

4

In [136]:
D5[0,3] # 2nd option: we can write this also

4

In [137]:
D5[2:,:2]

array([[ 9, 10]])

In [140]:
D5[3:,3:]

array([], shape=(0, 1), dtype=int64)